from io import BytesIO
from pathlib import Path

import fitz
from fastapi.testclient import TestClient

from app.main import app

client = TestClient(app)


def make_pdf_bytes_with_text(text: str) -> bytes:
    doc = fitz.open()
    page = doc.new_page()
    page.insert_text((72, 72), text)
    b = doc.tobytes()
    doc.close()
    return b


def test_extract_pdf_text_creates_text_json(temp_data_dir: Path):
    # 1) Upload a real PDF generated by PyMuPDF
    pdf_bytes = make_pdf_bytes_with_text("Hello PyMuPDF")
    files = [("files", ("sample.pdf", BytesIO(pdf_bytes), "application/pdf"))]
    r = client.post("/upload", files=files)
    assert r.status_code == 200, r.text

    up = r.json()
    doc_id = up["documents"][0]["doc_id"]

    # 2) Extract
    r2 = client.post(f"/documents/{doc_id}/extract-text")
    assert r2.status_code == 200, r2.text
    data = r2.json()
    assert data["status"] in ("extracted", "already_extracted")
    assert data["page_count"] == 1

    # 3) Read text.json
    r3 = client.get(f"/documents/{doc_id}/text")
    assert r3.status_code == 200, r3.text
    tj = r3.json()
    assert tj["doc_id"] == doc_id
    assert tj["page_count"] == 1
    assert "Hello PyMuPDF" in tj["pages"][0]["text"]
    assert tj["pages"][0]["source"] == "pymupdf"


def make_pdf_bytes_empty_page() -> bytes:
    doc = fitz.open()
    doc.new_page()  # no text
    b = doc.tobytes()
    doc.close()
    return b


def test_extract_marks_empty_pages(temp_data_dir: Path):
    pdf_bytes = make_pdf_bytes_empty_page()
    files = [("files", ("empty.pdf", BytesIO(pdf_bytes), "application/pdf"))]
    r = client.post("/upload", files=files)
    doc_id = r.json()["documents"][0]["doc_id"]

    r2 = client.post(f"/documents/{doc_id}/extract-text")
    assert r2.status_code == 200

    r3 = client.get(f"/documents/{doc_id}/text")
    tj = r3.json()
    assert tj["pages"][0]["is_empty"] is True


def test_extract_rejects_non_pdf(temp_data_dir: Path):
    # Upload png
    png = b"\x89PNG\r\n\x1a\nfake"
    files = [("files", ("img.png", BytesIO(png), "image/png"))]
    r = client.post("/upload", files=files)
    doc_id = r.json()["documents"][0]["doc_id"]

    r2 = client.post(f"/documents/{doc_id}/extract-text")
    assert r2.status_code == 400


def test_extract_rejects_bad_doc_id(temp_data_dir: Path):
    r = client.post("/documents/../../etc/passwd/extract-text")
    assert r.status_code in (400, 404)
